# Generated by Django 4.1 on 2022-08-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contributor_events_rename_extendeduser_collector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_name', models.CharField(max_length=122)),
                ('coordinator_phone', models.IntegerField()),
                ('coordinator_email', models.CharField(max_length=122)),
                ('event_name', models.CharField(max_length=122)),
                ('event_desc', models.CharField(max_length=122)),
                ('venue', models.CharField(max_length=122)),
                ('event_date', models.CharField(max_length=122)),
                ('time', models.CharField(max_length=122)),
            ],
        ),
        migrations.RenameModel(
            old_name='Collector',
            new_name='extendeduser',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
